import { quote } from './pricing'
import type { Category, Customer, Order, OrderItem, OrderStatus, Product } from './types'

export const CATEGORIES: Category[] = [
  { id: 'first-aid', name: 'עזרה ראשונה', blurb: 'ערכות, חבישות וחיטוי לפצעים שטחיים' },
  { id: 'monitors', name: 'מדדים רפואיים', blurb: 'מכשירי מדידה לשימוש ביתי' },
  { id: 'vitamins', name: 'ויטמינים ותוספים', blurb: 'תוספי תזונה ללא מרשם, לתצוגת מדף' },
  { id: 'hygiene', name: 'היגיינה', blurb: 'ניקיון יומיומי לידיים ולפה' },
  { id: 'ortho', name: 'תמיכות אורתופדיות', blurb: 'תמיכות ומדרסים לשימוש יומיומי' },
  { id: 'home', name: 'ציוד ביתי רפואי', blurb: 'נוחות, מדידה וארגון בבית' },
]

export const PRODUCTS: Product[] = [
  {
    id: 'kit',
    name: 'ערכת עזרה ראשונה ביתית',
    category: 'first-aid',
    price: 89,
    compareAt: 119,
    description: 'תיק קומפקטי עם ציוד בסיסי לטיפול ראשוני בבית. המוצר מוצג להדגמה ואינו מחליף טיפול רפואי.',
    specs: ['תיק בד עם רוכסן', 'כולל פלסטרים וגזה', 'מתאים למגירה או לרכב', 'משקל אריזה כ-400 גרם', 'ללא מרשם'],
    stock: 24,
    badge: 'sale',
    rating: 4.7,
    reviews: 86,
    tone: '#0f766e',
  },
  {
    id: 'plasters',
    name: 'פלסטרים אטומים למים',
    category: 'first-aid',
    price: 18,
    description: 'חבילת פלסטרים גמישים להגנה על שריטות קטנות. פריט מדף להדגמת החנות.',
    specs: ['40 יחידות במארז', 'מידות מעורבות', 'ציפוי עמיד למים', 'אריזה סגורה'],
    stock: 80,
    badge: 'popular',
    rating: 4.5,
    reviews: 142,
    tone: '#0d9488',
  },
  {
    id: 'bandage',
    name: 'תחבושת אלסטית',
    category: 'first-aid',
    price: 24,
    description: 'תחבושת נמתחת לעטיפה חיצונית. נוחה להצגה על המדף ובסל הדמו.',
    specs: ['רוחב 8 ס"מ', 'אורך 4 מטר', 'סגירה בווים', 'ניתנת לכביסה עדינה', 'יחידה אחת'],
    stock: 40,
    rating: 4.4,
    reviews: 63,
    tone: '#147d6f',
  },
  {
    id: 'gauze',
    name: 'גזה סטרילית',
    category: 'first-aid',
    price: 16,
    description: 'רפידות גזה באריזה אישית, להדגמת מוצר חבישה בסיסי.',
    specs: ['10 יחידות', 'אריזה אישית', 'גודל 5 על 5 ס"מ', 'שימוש חד-פעמי'],
    stock: 60,
    rating: 4.3,
    reviews: 41,
    tone: '#115e59',
  },
  {
    id: 'wipes',
    name: 'מגבוני חיטוי לפצעים',
    category: 'first-aid',
    price: 22,
    description: 'מגבונים לניקוי עור סביב שריטה שטחית. אינו תחליף לטיפול בפצע עמוק.',
    specs: ['20 מגבונים', 'אריזות בודדות', 'ללא מרשם', 'מתאים לתיק אישי', 'מוצר מדף'],
    stock: 50,
    badge: 'new',
    rating: 4.6,
    reviews: 28,
    tone: '#0f766e',
  },
  {
    id: 'ice',
    name: 'שקית קירור מיידית',
    category: 'first-aid',
    price: 27,
    description: 'שקית חד-פעמית שמתקררת בלחיצה. פריט נוחות לתצוגה, לא מכשיר טיפול.',
    specs: ['הפעלה בלחיצה', 'שימוש חד-פעמי', 'גודל כף יד', 'ללא הקפאה מראש'],
    stock: 30,
    rating: 4.2,
    reviews: 19,
    tone: '#0e7490',
  },
  {
    id: 'thermo',
    name: 'מדחום דיגיטלי מהיר',
    category: 'monitors',
    price: 39,
    compareAt: 49,
    description: 'מדחום ביתי עם תצוגה ספרתית וכיבוי אוטומטי. מודד חום ואינו נותן אבחנה.',
    specs: ['תצוגה גדולה', 'כיבוי אוטומטי', 'כולל סוללה להדגמה', 'נרתיק שמירה', 'יחידת מידה צלזיוס'],
    stock: 35,
    badge: 'popular',
    rating: 4.8,
    reviews: 210,
    tone: '#0e7490',
  },
  {
    id: 'bp',
    name: 'מד לחץ דם אוטומטי',
    category: 'monitors',
    price: 189,
    description: 'מד לחץ לזרוע עם תצוגה רחבה. הקריאה על המסך היא הדגמה ואינה ייעוץ רפואי.',
    specs: ['חפת לזרוע', 'מסך גדול', 'זיכרון 30 מדידות במכשיר', 'שקית אחסון', 'סוללות כלולות באריזת הדמו'],
    stock: 12,
    rating: 4.6,
    reviews: 97,
    tone: '#155e75',
  },
  {
    id: 'oxi',
    name: 'מד חמצן אצבע',
    category: 'monitors',
    price: 79,
    description: 'מכשיר אצבע קטן לתצוגת דופק וחמצן. אינו מכשיר חירום ואינו מחליף בדיקה רפואית.',
    specs: ['תצוגה דו-צבעית', 'כיבוי אוטומטי', 'משקל קל', 'נרתיק נשיאה'],
    stock: 20,
    rating: 4.5,
    reviews: 74,
    tone: '#0891b2',
  },
  {
    id: 'scale',
    name: 'משקל אדם דיגיטלי',
    category: 'monitors',
    price: 99,
    description: 'משקל רצפתי עם ספרות ברורות. מציג משקל בלבד.',
    specs: ['משטח זכוכית', 'עד 180 ק"ג בתצוגה', 'דיוק של 100 גרם', 'סוללות כלולות'],
    stock: 15,
    rating: 4.1,
    reviews: 53,
    tone: '#164e63',
  },
  {
    id: 'glucose',
    name: 'מד סוכר ביתי',
    category: 'monitors',
    price: 129,
    description: 'ערכת מדידה ביתית להדגמת מדף. התוצאה על המסך אינה המלצת טיפול.',
    specs: ['מכשיר אחד', '10 סטריפים באריזת הדמו', 'נרתיק', 'מסך מואר', 'ללא מרשם למכשיר'],
    stock: 10,
    badge: 'new',
    rating: 4.4,
    reviews: 36,
    tone: '#0f766e',
  },
  {
    id: 'vd',
    name: 'ויטמין D3',
    category: 'vitamins',
    price: 49,
    description: 'תוסף תזונה במארז דמו. אינו תחליף לייעוץ תזונתי או רפואי.',
    specs: ['60 כמוסות', 'צנצנת עם מכסה', 'ללא מרשם', 'אחסון במקום יבש'],
    stock: 40,
    badge: 'popular',
    rating: 4.7,
    reviews: 166,
    tone: '#b45309',
  },
  {
    id: 'vc',
    name: 'ויטמין C',
    category: 'vitamins',
    price: 42,
    compareAt: 55,
    description: 'טבליות תוסף במארז מבצע להדגמה. אין כאן הוראות נטילה רפואיות.',
    specs: ['30 טבליות', 'קופסה קשיחה', 'ללא מרשם', 'פריט מדף'],
    stock: 36,
    badge: 'sale',
    rating: 4.4,
    reviews: 88,
    tone: '#c2410c',
  },
  {
    id: 'multi',
    name: 'מולטי ויטמין יומי',
    category: 'vitamins',
    price: 69,
    description: 'מארז תוסף משולב לתצוגת החנות. אינו אבחנה ואינו מרשם.',
    specs: ['30 מנות באריזה', 'בקבוק אטום', 'ללא מרשם', 'תווית בעברית'],
    stock: 28,
    rating: 4.5,
    reviews: 121,
    tone: '#a16207',
  },
  {
    id: 'omega',
    name: 'אומגה 3',
    category: 'vitamins',
    price: 79,
    description: 'כמוסות שמן דגים כתוסף תזונה לתצוגה. אין במארז הבטחה רפואית.',
    specs: ['60 כמוסות', 'בקבוק כהה', 'ללא מרשם', 'אריזה חתומה'],
    stock: 22,
    rating: 4.3,
    reviews: 70,
    tone: '#9a3412',
  },
  {
    id: 'mag',
    name: 'מגנזיום ציטראט',
    category: 'vitamins',
    price: 54,
    description: 'אבקה תוספת במארז ביתי להדגמה. אינו מחליף ייעוץ.',
    specs: ['150 גרם', 'כפית מדידה באריזה', 'ללא מרשם', 'שקית פנימית'],
    stock: 26,
    rating: 4.6,
    reviews: 59,
    tone: '#b45309',
  },
  {
    id: 'probiotic',
    name: 'פרוביוטיקה יומית',
    category: 'vitamins',
    price: 89,
    description: 'כמוסות תוסף במקרר מדומה על המדף. מוצר תצוגה ללא מרשם.',
    specs: ['30 כמוסות', 'אריזת בליסטר', 'ללא מרשם', 'תווית דמו', 'חדש במדף'],
    stock: 18,
    badge: 'new',
    rating: 4.2,
    reviews: 24,
    tone: '#ca8a04',
  },
  {
    id: 'gel',
    name: 'ג׳ל חיטוי לידיים',
    category: 'hygiene',
    price: 19,
    description: 'בקבוק אישי לניקוי ידיים כשאין כיור. פריט היגיינה רגיל.',
    specs: ['100 מ"ל', 'מכסה נפתח', 'מתאים לתיק', 'ללא שטיפה'],
    stock: 100,
    badge: 'popular',
    rating: 4.6,
    reviews: 240,
    tone: '#0369a1',
  },
  {
    id: 'wetwipes',
    name: 'מגבונים לחים עדינים',
    category: 'hygiene',
    price: 16,
    description: 'אריזת מגבונים לניקוי ידיים ומשטחים קטנים.',
    specs: ['72 יחידות', 'מכסה מתהפך', 'ללא בישום חזק', 'אריזה גמישה'],
    stock: 70,
    rating: 4.3,
    reviews: 91,
    tone: '#0284c7',
  },
  {
    id: 'soap',
    name: 'סבון ידיים אנטיבקטריאלי',
    category: 'hygiene',
    price: 21,
    description: 'סבון נוזלי לשימוש יומיומי בכיור. מוצר ניקיון, לא תרופה.',
    specs: ['500 מ"ל', 'משאבה', 'ניחוח עדין', 'בקבוק שקוף'],
    stock: 45,
    rating: 4.4,
    reviews: 77,
    tone: '#075985',
  },
  {
    id: 'masks',
    name: 'מסכות פנים חד-פעמיות',
    category: 'hygiene',
    price: 25,
    description: 'חבילת מסכות תלת-שכבתיות. במלאי הדמו הפריט אזל, כדי להציג מצב קצה.',
    specs: ['50 יחידות', 'תלת-שכבתי', 'גומי אוזניים', 'אריזה סגורה'],
    stock: 0,
    rating: 4.1,
    reviews: 134,
    tone: '#64748b',
  },
  {
    id: 'mouthwash',
    name: 'שטיפת פה עדינה',
    category: 'hygiene',
    price: 28,
    description: 'שטיפת פה יומיומית בטעם עדין. מוצר היגיינה ללא מרשם.',
    specs: ['400 מ"ל', 'כוס מדידה על המכסה', 'ללא אלכוהול', 'אריזה חתומה'],
    stock: 33,
    rating: 4.5,
    reviews: 68,
    tone: '#0369a1',
  },
  {
    id: 'back',
    name: 'חגורת תמיכה לגב',
    category: 'ortho',
    price: 119,
    compareAt: 149,
    description: 'חגורה אלסטית לתמיכה חיצונית בזמן ישיבה או הליכה. אינה טיפול רפואי.',
    specs: ['מידות מתכווננות', 'רצועות צד', 'בד נושם', 'סגירת סקוטש', 'הוראות מידה על האריזה'],
    stock: 14,
    badge: 'sale',
    rating: 4.4,
    reviews: 58,
    tone: '#6d28d9',
  },
  {
    id: 'insole',
    name: 'מדרסי ג׳ל',
    category: 'ortho',
    price: 45,
    description: 'זוג מדרסים רכים לנעל יומיומית. פריט נוחות להדגמה.',
    specs: ['זוג אחד', 'ג׳ל רך', 'ניתן לגזירה לפי המידה', 'מתאים לנעל סגורה'],
    stock: 40,
    badge: 'popular',
    rating: 4.6,
    reviews: 102,
    tone: '#7c3aed',
  },
  {
    id: 'knee',
    name: 'תומך ברך אלסטי',
    category: 'ortho',
    price: 59,
    description: 'שרוול ברך חלק לפעילות יומיומית. תמיכה חיצונית בלבד.',
    specs: ['מידה אוניברסלית', 'בד נושם', 'תפרים שטוחים', 'יחידה אחת'],
    stock: 22,
    rating: 4.3,
    reviews: 47,
    tone: '#5b21b6',
  },
  {
    id: 'ankle',
    name: 'תומך קרסול',
    category: 'ortho',
    price: 49,
    description: 'תומך דק מתחת לגרב. מוצר מדף, לא קיבוע רפואי.',
    specs: ['זוג', 'גזרה נמוכה', 'אלסטי', 'צבע שחור'],
    stock: 20,
    rating: 4.2,
    reviews: 33,
    tone: '#4c1d95',
  },
  {
    id: 'neck',
    name: 'כרית תמיכה לצוואר',
    category: 'ortho',
    price: 79,
    description: 'כרית נסיעה לצוואר, לתצוגת נוחות. אינה מכשיר שיקום.',
    specs: ['קצף זיכרון', 'כיסוי נשלף', 'מתאים למושב', 'גודל קומפקטי', 'חדש במדף'],
    stock: 16,
    badge: 'new',
    rating: 4.5,
    reviews: 21,
    tone: '#7c3aed',
  },
  {
    id: 'neb',
    name: 'מכשיר אינהלציה ביתי',
    category: 'home',
    price: 249,
    description: 'מדחס שולחני להדגמת ציוד ביתי. ההפעלה בחנות היא תצוגה בלבד, בלי חומר רפואי.',
    specs: ['יחידת מדחס', 'מסכה ומסיכה באריזה', 'צינור אוויר', 'תיק נשיאה', 'מתח חשמל ביתי'],
    stock: 8,
    rating: 4.7,
    reviews: 44,
    tone: '#115e59',
  },
  {
    id: 'heat',
    name: 'כרית חימום חשמלית',
    category: 'home',
    price: 99,
    description: 'כרית בד עם חום עדין לשעת מנוחה. יש לכבות אותה בתום השימוש.',
    specs: ['3 דרגות חום', 'כיבוי אוטומטי', 'כיסוי רך', 'כבל ארוך'],
    stock: 11,
    rating: 4.3,
    reviews: 39,
    tone: '#0f766e',
  },
  {
    id: 'cane',
    name: 'מקל הליכה מתקפל',
    category: 'home',
    price: 69,
    description: 'מקל אלומיניום מתקפל עם ידית רכה. אביזר הליכה להדגמה.',
    specs: ['גובה מתכוונן', 'מתקפל ל-4', 'רצועת יד', 'פקק גומי'],
    stock: 9,
    rating: 4.4,
    reviews: 27,
    tone: '#134e4a',
  },
  {
    id: 'shower',
    name: 'כיסא רחצה מתקפל',
    category: 'home',
    price: 189,
    description: 'מושב פלסטיק עם רגליים גומי למקלחת. ציוד נוחות ביתי.',
    specs: ['מתקפל לאחסון', 'רגליים נגד החלקה', 'חורים לניקוז', 'הרכבה בלי כלים'],
    stock: 6,
    rating: 4.6,
    reviews: 18,
    tone: '#115e59',
  },
  {
    id: 'pillbox',
    name: 'קופסת תרופות שבועית',
    category: 'home',
    price: 22,
    description: 'מארגן פלסטיק עם תא לכל יום. כלי אחסון בלבד, בלי תרופות ובלי הנחיות נטילה.',
    specs: ['7 תאים', 'מכסה שקוף', 'אותיות על המכסה', 'פלסטיק קשיח'],
    stock: 50,
    rating: 4.2,
    reviews: 80,
    tone: '#0f766e',
  },
]

function line(id: string, qty: number): OrderItem {
  const product = PRODUCTS.find((item) => item.id === id)
  if (!product) throw new Error(`מוצר חסר: ${id}`)
  return { productId: product.id, name: product.name, price: product.price, qty }
}

function buildSeed(
  id: string,
  createdAt: string,
  status: OrderStatus,
  customer: Customer,
  entries: Array<[string, number]>,
  coupon?: string,
): Order {
  const items = entries.map(([productId, qty]) => line(productId, qty))
  const subtotal = items.reduce((sum, item) => sum + item.price * item.qty, 0)
  const priced = quote(subtotal, coupon === 'DEMO10')
  return { id, createdAt, status, customer, items, ...priced, coupon }
}

export const SEED_ORDERS: Order[] = [
  buildSeed(
    'MED-10041',
    '2026-09-20T09:30:00.000Z',
    'delivered',
    { name: 'דנה לדוגמה', phone: '050-0000001', city: 'תל אביב', address: 'רחוב ההדגמה 1' },
    [
      ['thermo', 1],
      ['gel', 2],
    ],
  ),
  buildSeed(
    'MED-10042',
    '2026-09-24T14:10:00.000Z',
    'shipped',
    { name: 'יונתן לדוגמה', phone: '050-0000002', city: 'חיפה', address: 'שדרות הדמו 12' },
    [
      ['bp', 1],
      ['knee', 1],
    ],
    'DEMO10',
  ),
  buildSeed(
    'MED-10043',
    '2026-09-26T11:05:00.000Z',
    'packing',
    { name: 'מיכל לדוגמה', phone: '050-0000003', city: 'ירושלים', address: 'סמטת התצוגה 4' },
    [['neb', 1]],
  ),
  buildSeed(
    'MED-10044',
    '2026-09-28T07:45:00.000Z',
    'received',
    { name: 'עומר לדוגמה', phone: '050-0000004', city: 'באר שבע', address: 'כיכר המדף 8' },
    [
      ['vd', 2],
      ['plasters', 1],
    ],
  ),
]

export const STATUS_FLOW: OrderStatus[] = ['received', 'packing', 'shipped', 'delivered']

export const STATUS_LABEL: Record<OrderStatus, string> = {
  received: 'התקבלה',
  packing: 'נארזת',
  shipped: 'יצאה למשלוח',
  delivered: 'נמסרה',
}

export function productImage(product: string | { id: string; image?: string }) {
  if (typeof product === 'string') return `/products/${product}.png`
  return product.image || `/products/${product.id}.png`
}

export function getProduct(id: string) {
  return PRODUCTS.find((product) => product.id === id)
}

export function getCategory(id: string) {
  return CATEGORIES.find((category) => category.id === id)
}
