import { quote } from './pricing'
import type { Category, Customer, Order, OrderItem, OrderStatus, Product } from './types'

export const CATEGORIES: Category[] = [
  { id: 'first-aid', name: 'עזרה ראשונה', blurb: 'ערכות, חבישות וחיטוי לפצעים שטחיים' },
  { id: 'monitors', name: 'מדדים רפואיים', blurb: 'מכשירי מדידה לשימוש ביתי' },
  { id: 'vitamins', name: 'ויטמינים ותוספים', blurb: 'תוספי תזונה ללא מרשם, לתצוגת מדף' },
  { id: 'hygiene', name: 'היגיינה', blurb: 'ניקיון יומיומי לידיים ולפה' },
  { id: 'ortho', name: 'תמיכות אורתופדיות', blurb: 'תמיכות ומדרסים לשימוש יומיומי' },
  { id: 'home', name: 'ציוד ביתי רפואי', blurb: 'נוחות, מדידה וארגון בבית' },
]

export const PRODUCTS: Product[] = [
  {
    id: 'kit',
    name: 'ערכת עזרה ראשונה ביתית',
    category: 'first-aid',
    price: 89,
    compareAt: 119,
    description: 'תיק קומפקטי עם ציוד בסיסי לטיפול ראשוני בבית. המוצר מוצג להדגמה ואינו מחליף טיפול רפואי.',
    specs: ['תיק בד עם רוכסן', 'כולל פלסטרים וגזה', 'מתאים למגירה או לרכב', 'משקל אריזה כ-400 גרם', 'ללא מרשם'],
    stock: 24,
    badge: 'sale',
    rating: 4.7,
    reviews: 86,
    tone: '#0f766e',
  },
  {
    id: 'plasters',
    name: 'פלסטרים אטומים למים',
    category: 'first-aid',
    price: 18,
    description: 'חבילת פלסטרים גמישים להגנה על שריטות קטנות. פריט מדף להדגמת החנות.',
    specs: ['40 יחידות במארז', 'מידות מעורבות', 'ציפוי עמיד למים', 'אריזה סגורה'],
    stock: 80,
    badge: 'popular',
    rating: 4.5,
    reviews: 142,
    tone: '#0d9488',
  },
  {
    id: 'bandage',
    name: 'תחבושת אלסטית',
    category: 'first-aid',
    price: 24,
    description: 'תחבושת נמתחת לעטיפה חיצונית. נוחה להצגה על המדף ובסל הדמו.',
    specs: ['רוחב 8 ס"מ', 'אורך 4 מטר', 'סגירה בווים', 'ניתנת לכביסה עדינה', 'יחידה אחת'],
    stock: 40,
    rating: 4.4,
    reviews: 63,
    tone: '#147d6f',
  },
  {
    id: 'gauze',
    name: 'גזה סטרילית',
    category: 'first-aid',
    price: 16,
    description: 'רפידות גזה באריזה אישית, להדגמת מוצר חבישה בסיסי.',
    specs: ['10 יחידות', 'אריזה אישית', 'גודל 5 על 5 ס"מ', 'שימוש חד-פעמי'],
    stock: 60,
    rating: 4.3,
    reviews: 41,
    tone: '#115e59',
  },
  {
    id: 'wipes',
    name: 'מגבוני חיטוי לפצעים',
    category: 'first-aid',
    price: 22,
    description: 'מגבונים לניקוי עור סביב שריטה שטחית. אינו תחליף לטיפול בפצע עמוק.',
    specs: ['20 מגבונים', 'אריזות בודדות', 'ללא מרשם', 'מתאים לתיק אישי', 'מוצר מדף'],
    stock: 50,
    badge: 'new',
    rating: 4.6,
    reviews: 28,
    tone: '#0f766e',
  },
  {
    id: 'ice',
    name: 'שקית קירור מיידית',
    category: 'first-aid',
    price: 27,
    description: 'שקית חד-פעמית שמתקררת בלחיצה. פריט נוחות לתצוגה, לא מכשיר טיפול.',
    specs: ['הפעלה בלחיצה', 'שימוש חד-פעמי', 'גודל כף יד', 'ללא הקפאה מראש'],
    stock: 30,
    rating: 4.2,
    reviews: 19,
    tone: '#0e7490',
  },
  {
    id: 'thermo',
    name: 'מדחום דיגיטלי מהיר',
    category: 'monitors',
    price: 39,
    compareAt: 49,
    description: 'מדחום ביתי עם תצוגה ספרתית וכיבוי אוטומטי. מודד חום ואינו נותן אבחנה.',
    specs: ['תצוגה גדולה', 'כיבוי אוטומטי', 'כולל סוללה להדגמה', 'נרתיק שמירה', 'יחידת מידה צלזיוס'],
    stock: 35,
    badge: 'popular',
    rating: 4.8,
    reviews: 210,
    tone: '#0e7490',
  },
  {
    id: 'bp',
    name: 'מד לחץ דם אוטומטי',
    category: 'monitors',
    price: 189,
    description: 'מד לחץ לזרוע עם תצוגה רחבה. הקריאה על המסך היא הדגמה ואינה ייעוץ רפואי.',
    specs: ['חפת לזרוע', 'מסך גדול', 'זיכרון 30 מדידות במכשיר', 'שקית אחסון', 'סוללות כלולות באריזת הדמו'],
    stock: 12,
    rating: 4.6,
    reviews: 97,
    tone: '#155e75',
  },
  {
    id: 'oxi',
    name: 'מד חמצן אצבע',
    category: 'monitors',
    price: 79,
    description: 'מכשיר אצבע קטן לתצוגת דופק וחמצן. אינו מכשיר חירום ואינו מחליף בדיקה רפואית.',
    specs: ['תצוגה דו-צבעית', 'כיבוי אוטומטי', 'משקל קל', 'נרתיק נשיאה'],
    stock: 20,
    rating: 4.5,
    reviews: 74,
    tone: '#0891b2',
  },
  {
    id: 'scale',
    name: 'משקל אדם דיגיטלי',
    category: 'monitors',
    price: 99,
    description: 'משקל רצפתי עם ספרות ברורות. מציג משקל בלבד.',
    specs: ['משטח זכוכית', 'עד 180 ק"ג בתצוגה', 'דיוק של 100 גרם', 'סוללות כלולות'],
    stock: 15,
    rating: 4.1,
    reviews: 53,
    tone: '#164e63',
  },
  {
    id: 'glucose',
    name: 'מד סוכר ביתי',
    category: 'monitors',
    price: 129,
    description: 'ערכת מדידה ביתית להדגמת מדף. התוצאה על המסך אינה המלצת טיפול.',
    specs: ['מכשיר אחד', '10 סטריפים באריזת הדמו', 'נרתיק', 'מסך מואר', 'ללא מרשם למכשיר'],
    stock: 10,
    badge: 'new',
    rating: 4.4,
    reviews: 36,
    tone: '#0f766e',
  },
  {
    id: 'vd',
    name: 'ויטמין D3',
    category: 'vitamins',
    price: 49,
    description: 'תוסף תזונה במארז דמו. אינו תחליף לייעוץ תזונתי או רפואי.',
    specs: ['60 כמוסות', 'צנצנת עם מכסה', 'ללא מרשם', 'אחסון במקום יבש'],
    stock: 40,
    badge: 'popular',
    rating: 4.7,
    reviews: 166,
    tone: '#b45309',
  },
  {
    id: 'vc',
    name: 'ויטמין C',
    category: 'vitamins',
    price: 42,
    compareAt: 55,
    description: 'טבליות תוסף במארז מבצע להדגמה. אין כאן הוראות נטילה רפואיות.',
    specs: ['30 טבליות', 'קופסה קשיחה', 'ללא מרשם', 'פריט מדף'],
    stock: 36,
    badge: 'sale',
    rating: 4.4,
    reviews: 88,
    tone: '#c2410c',
  },
  {
    id: 'multi',
    name: 'מולטי ויטמין יומי',
    category: 'vitamins',
    price: 69,
    description: 'מארז תוסף משולב לתצוגת החנות. אינו אבחנה ואינו מרשם.',
    specs: ['30 מנות באריזה', 'בקבוק אטום', 'ללא מרשם', 'תווית בעברית'],
    stock: 28,
    rating: 4.5,
    reviews: 121,
    tone: '#a16207',
  },
  {
    id: 'omega',
    name: 'אומגה 3',
    category: 'vitamins',
    price: 79,
    description: 'כמוסות שמן דגים כתוסף תזונה לתצוגה. אין במארז הבטחה רפואית.',
    specs: ['60 כמוסות', 'בקבוק כהה', 'ללא מרשם', 'אריזה חתומה'],
    stock: 22,
    rating: 4.3,
    reviews: 70,
    tone: '#9a3412',
  },
  {
    id: 'mag',
    name: 'מגנזיום ציטראט',
    category: 'vitamins',
    price: 54,
    description: 'אבקה תוספת במארז ביתי להדגמה. אינו מחליף ייעוץ.',
    specs: ['150 גרם', 'כפית מדידה באריזה', 'ללא מרשם', 'שקית פנימית'],
    stock: 26,
    rating: 4.6,
    reviews: 59,
    tone: '#b45309',
  },
  {
    id: 'probiotic',
    name: 'פרוביוטיקה יומית',
    category: 'vitamins',
    price: 89,
    description: 'כמוסות תוסף במקרר מדומה על המדף. מוצר תצוגה ללא מרשם.',
    specs: ['30 כמוסות', 'אריזת בליסטר', 'ללא מרשם', 'תווית דמו', 'חדש במדף'],
    stock: 18,
    badge: 'new',
    rating: 4.2,
    reviews: 24,
    tone: '#ca8a04',
  },
  {
    id: 'gel',
    name: 'ג׳ל חיטוי לידיים',
    category: 'hygiene',
    price: 19,
    description: 'בקבוק אישי לניקוי ידיים כשאין כיור. פריט היגיינה רגיל.',
    specs: ['100 מ"ל', 'מכסה נפתח', 'מתאים לתיק', 'ללא שטיפה'],
    stock: 100,
    badge: 'popular',
    rating: 4.6,
    reviews: 240,
    tone: '#0369a1',
  },
  {
    id: 'wetwipes',
    name: 'מגבונים לחים עדינים',
    category: 'hygiene',
    price: 16,
    description: 'אריזת מגבונים לניקוי ידיים ומשטחים קטנים.',
    specs: ['72 יחידות', 'מכסה מתהפך', 'ללא בישום חזק', 'אריזה גמישה'],
    stock: 70,
    rating: 4.3,
    reviews: 91,
    tone: '#0284c7',
  },
  {
    id: 'soap',
    name: 'סבון ידיים אנטיבקטריאלי',
    category: 'hygiene',
    price: 21,
    description: 'סבון נוזלי לשימוש יומיומי בכיור. מוצר ניקיון, לא תרופה.',
    specs: ['500 מ"ל', 'משאבה', 'ניחוח עדין', 'בקבוק שקוף'],
    stock: 45,
    rating: 4.4,
    reviews: 77,
    tone: '#075985',
  },
  {
    id: 'masks',
    name: 'מסכות פנים חד-פעמיות',
    category: 'hygiene',
    price: 25,
    description: 'חבילת מסכות תלת-שכבתיות. במלאי הדמו הפריט אזל, כדי להציג מצב קצה.',
    specs: ['50 יחידות', 'תלת-שכבתי', 'גומי אוזניים', 'אריזה סגורה'],
    stock: 0,
    rating: 4.1,
    reviews: 134,
    tone: '#64748b',
  },
  {
    id: 'mouthwash',
    name: 'שטיפת פה עדינה',
    category: 'hygiene',
    price: 28,
    description: 'שטיפת פה יומיומית בטעם עדין. מוצר היגיינה ללא מרשם.',
    specs: ['400 מ"ל', 'כוס מדידה על המכסה', 'ללא אלכוהול', 'אריזה חתומה'],
    stock: 33,
    rating: 4.5,
    reviews: 68,
    tone: '#0369a1',
  },
  {
    id: 'back',
    name: 'חגורת תמיכה לגב',
    category: 'ortho',
    price: 119,
    compareAt: 149,
    description: 'חגורה אלסטית לתמיכה חיצונית בזמן ישיבה או הליכה. אינה טיפול רפואי.',
    specs: ['מידות מתכווננות', 'רצועות צד', 'בד נושם', 'סגירת סקוטש', 'הוראות מידה על האריזה'],
    stock: 14,
    badge: 'sale',
    rating: 4.4,
    reviews: 58,
    tone: '#6d28d9',
  },
  {
    id: 'insole',
    name: 'מדרסי ג׳ל',
    category: 'ortho',
    price: 45,
    description: 'זוג מדרסים רכים לנעל יומיומית. פריט נוחות להדגמה.',
    specs: ['זוג אחד', 'ג׳ל רך', 'ניתן לגזירה לפי המידה', 'מתאים לנעל סגורה'],
    stock: 40,
    badge: 'popular',
    rating: 4.6,
    reviews: 102,
    tone: '#7c3aed',
  },
  {
    id: 'knee',
    name: 'תומך ברך אלסטי',
    category: 'ortho',
    price: 59,
    description: 'שרוול ברך חלק לפעילות יומיומית. תמיכה חיצונית בלבד.',
    specs: ['מידה אוניברסלית', 'בד נושם', 'תפרים שטוחים', 'יחידה אחת'],
    stock: 22,
    rating: 4.3,
    reviews: 47,
    tone: '#5b21b6',
  },
  {
    id: 'ankle',
    name: 'תומך קרסול',
    category: 'ortho',
    price: 49,
    description: 'תומך דק מתחת לגרב. מוצר מדף, לא קיבוע רפואי.',
    specs: ['זוג', 'גזרה נמוכה', 'אלסטי', 'צבע שחור'],
    stock: 20,
    rating: 4.2,
    reviews: 33,
    tone: '#4c1d95',
  },
  {
    id: 'neck',
    name: 'כרית תמיכה לצוואר',
    category: 'ortho',
    price: 79,
    description: 'כרית נסיעה לצוואר, לתצוגת נוחות. אינה מכשיר שיקום.',
    specs: ['קצף זיכרון', 'כיסוי נשלף', 'מתאים למושב', 'גודל קומפקטי', 'חדש במדף'],
    stock: 16,
    badge: 'new',
    rating: 4.5,
    reviews: 21,
    tone: '#7c3aed',
  },
  {
    id: 'neb',
    name: 'מכשיר אינהלציה ביתי',
    category: 'home',
    price: 249,
    description: 'מדחס שולחני להדגמת ציוד ביתי. ההפעלה בחנות היא תצוגה בלבד, בלי חומר רפואי.',
    specs: ['יחידת מדחס', 'מסכה ומסיכה באריזה', 'צינור אוויר', 'תיק נשיאה', 'מתח חשמל ביתי'],
    stock: 8,
    rating: 4.7,
    reviews: 44,
    tone: '#115e59',
  },
  {
    id: 'heat',
    name: 'כרית חימום חשמלית',
    category: 'home',
    price: 99,
    description: 'כרית בד עם חום עדין לשעת מנוחה. יש לכבות אותה בתום השימוש.',
    specs: ['3 דרגות חום', 'כיבוי אוטומטי', 'כיסוי רך', 'כבל ארוך'],
    stock: 11,
    rating: 4.3,
    reviews: 39,
    tone: '#0f766e',
  },
  {
    id: 'cane',
    name: 'מקל הליכה מתקפל',
    category: 'home',
    price: 69,
    description: 'מקל אלומיניום מתקפל עם ידית רכה. אביזר הליכה להדגמה.',
    specs: ['גובה מתכוונן', 'מתקפל ל-4', 'רצועת יד', 'פקק גומי'],
    stock: 9,
    rating: 4.4,
    reviews: 27,
    tone: '#134e4a',
  },
  {
    id: 'shower',
    name: 'כיסא רחצה מתקפל',
    category: 'home',
    price: 189,
    description: 'מושב פלסטיק עם רגליים גומי למקלחת. ציוד נוחות ביתי.',
    specs: ['מתקפל לאחסון', 'רגליים נגד החלקה', 'חורים לניקוז', 'הרכבה בלי כלים'],
    stock: 6,
    rating: 4.6,
    reviews: 18,
    tone: '#115e59',
  },
  {
    id: 'pillbox',
    name: 'קופסת תרופות שבועית',
    category: 'home',
    price: 22,
    description: 'מארגן פלסטיק עם תא לכל יום. כלי אחסון בלבד, בלי תרופות ובלי הנחיות נטילה.',
    specs: ['7 תאים', 'מכסה שקוף', 'אותיות על המכסה', 'פלסטיק קשיח'],
    stock: 50,
    rating: 4.2,
    reviews: 80,
    tone: '#0f766e',
  },
  {
    id: 'grab-fold',
    name: 'מעקה אחיזה מתקפל',
    category: 'home',
    price: 149,
    description: 'מעקה לקיר, מתקפל כשלא בשימוש. ליד מיטה או אמבט.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.6,
    reviews: 14,
    tone: '#163a66',
    image: '/products/grab-fold.jpg',
  },
  {
    id: 'wheel-power',
    name: 'כסא גלגלים חשמלי',
    category: 'home',
    price: 2490,
    description: 'כסא עם מנוע וג\'ויסטיק, לשימוש ביתי. פריט תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 3,
    badge: 'new',
    rating: 4.7,
    reviews: 9,
    tone: '#163a66',
    image: '/products/wheel-power.jpg',
  },
  {
    id: 'cane-tele',
    name: 'מקל הליכה טלסקופי',
    category: 'home',
    price: 79,
    description: 'מקל אלומיניום עם גובה מתכוונן וידית אחיזה.',
    specs: ['פריט תצוגה'],
    stock: 16,
    badge: 'new',
    rating: 4.5,
    reviews: 22,
    tone: '#163a66',
    image: '/products/cane-tele.jpg',
  },
  {
    id: 'shower-back',
    name: 'כיסא רחצה עם משענת',
    category: 'home',
    price: 219,
    description: 'מושב עם גב, ידיות ורגליים נגד החלקה למקלחת.',
    specs: ['פריט תצוגה'],
    stock: 6,
    badge: 'new',
    rating: 4.6,
    reviews: 11,
    tone: '#163a66',
    image: '/products/shower-back.jpg',
  },
  {
    id: 'neck-massager',
    name: 'מכשיר עיסוי לצוואר',
    category: 'home',
    price: 189,
    description: 'עיסוי חיצוני לצוואר ולכתפיים בשעת מנוחה.',
    specs: ['פריט תצוגה'],
    stock: 10,
    badge: 'new',
    rating: 4.4,
    reviews: 18,
    tone: '#163a66',
    image: '/products/neck-massager.jpg',
  },
  {
    id: 'bath-bench',
    name: 'ספסל העברה לאמבט',
    category: 'home',
    price: 249,
    description: 'ספסל עם משענת, חלק ממנו מחוץ לאמבט כדי לשבת ולהיכנס.',
    specs: ['פריט תצוגה'],
    stock: 5,
    badge: 'new',
    rating: 4.5,
    reviews: 8,
    tone: '#163a66',
    image: '/products/bath-bench.jpg',
  },
  {
    id: 'shower-stool',
    name: 'שרפרף רחצה',
    category: 'home',
    price: 99,
    description: 'מושב עגול עם רגליים מתכווננות ופקקי גומי.',
    specs: ['פריט תצוגה'],
    stock: 12,
    badge: 'new',
    rating: 4.4,
    reviews: 16,
    tone: '#163a66',
    image: '/products/shower-stool.jpg',
  },
  {
    id: 'walker-std',
    name: 'הליכון אלומיניום',
    category: 'home',
    price: 189,
    description: 'הליכון קל עם גובה מתכוונן. דגם עם גלגלים או בלי.',
    specs: ['פריט תצוגה'],
    stock: 7,
    badge: 'new',
    rating: 4.5,
    reviews: 13,
    tone: '#163a66',
    image: '/products/walker-std.jpg',
  },
  {
    id: 'air-pad',
    name: 'מזרן אוויר עם משאבה',
    category: 'home',
    price: 690,
    description: 'מזרן תאים ומשאבה למיטה סיעודית. ציוד ביתי להדגמה.',
    specs: ['פריט תצוגה'],
    stock: 4,
    badge: 'new',
    rating: 4.6,
    reviews: 7,
    tone: '#163a66',
    image: '/products/air-pad.jpg',
  },
  {
    id: 'care-bed',
    name: 'מיטה סיעודית',
    category: 'home',
    price: 3890,
    description: 'מיטה עם גלגלים, מעקה ושליטה חשמלית. פריט תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 2,
    badge: 'new',
    rating: 4.8,
    reviews: 5,
    tone: '#163a66',
    image: '/products/care-bed.jpg',
  },
  {
    id: 'ankle-weight',
    name: 'משקולת קרסול רכה',
    category: 'ortho',
    price: 49,
    description: 'רצועת משקל רכה לקרסול, לאימון קל בבית.',
    specs: ['פריט תצוגה'],
    stock: 20,
    badge: 'new',
    rating: 4.3,
    reviews: 19,
    tone: '#163a66',
    image: '/products/ankle-weight.jpg',
  },
  {
    id: 'thumb-glove',
    name: 'כפפת תמיכה לאגודל',
    category: 'ortho',
    price: 69,
    description: 'כפפה עם חיזוק לאגודל ולשורש כף היד.',
    specs: ['פריט תצוגה'],
    stock: 14,
    badge: 'new',
    rating: 4.5,
    reviews: 21,
    tone: '#163a66',
    image: '/products/thumb-glove.jpg',
  },
  {
    id: 'ankle-strap',
    name: 'סד קרסול עם רצועות',
    category: 'ortho',
    price: 89,
    description: 'סד קל עם סקוטש, ננעל מעל הקרסול.',
    specs: ['פריט תצוגה'],
    stock: 12,
    badge: 'new',
    rating: 4.4,
    reviews: 17,
    tone: '#163a66',
    image: '/products/ankle-strap.jpg',
  },
  {
    id: 'ankle-rigid',
    name: 'סד קרסול קשיח',
    category: 'ortho',
    price: 119,
    description: 'סד עם חיזוקים בצדדים ורצועות סגירה.',
    specs: ['פריט תצוגה'],
    stock: 10,
    badge: 'new',
    rating: 4.5,
    reviews: 12,
    tone: '#163a66',
    image: '/products/ankle-rigid.jpg',
  },
  {
    id: 'shoulder-stab',
    name: 'מייצב כתף',
    category: 'ortho',
    price: 149,
    description: 'מיתלה עם רצועה אלכסונית לתמיכה בכתף.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.4,
    reviews: 10,
    tone: '#163a66',
    image: '/products/shoulder-stab.jpg',
  },
  {
    id: 'wrist-strap',
    name: 'סד שורש כף יד',
    category: 'ortho',
    price: 79,
    description: 'סד קצר עם סקוטש, משאיר את האצבעות חופשיות.',
    specs: ['פריט תצוגה'],
    stock: 18,
    badge: 'new',
    rating: 4.5,
    reviews: 24,
    tone: '#163a66',
    image: '/products/wrist-strap.jpg',
  },
  {
    id: 'heel-cups',
    name: 'כריות עקב מסיליקון',
    category: 'ortho',
    price: 39,
    description: 'זוג כריות רכות לעקב, נכנסות לנעל.',
    specs: ['פריט תצוגה'],
    stock: 24,
    badge: 'new',
    rating: 4.3,
    reviews: 27,
    tone: '#163a66',
    image: '/products/heel-cups.jpg',
  },
  {
    id: 'neck-collar',
    name: 'צווארון צוואר',
    category: 'ortho',
    price: 99,
    description: 'צווארון עם פתח קדמי וסגירת סקוטש.',
    specs: ['פריט תצוגה'],
    stock: 9,
    badge: 'new',
    rating: 4.4,
    reviews: 11,
    tone: '#163a66',
    image: '/products/neck-collar.jpg',
  },
  {
    id: 'posture-strap',
    name: 'רצועת יציבה',
    category: 'ortho',
    price: 89,
    description: 'רצועות גב בצורת איקס, נלבשות מעל חולצה.',
    specs: ['פריט תצוגה'],
    stock: 15,
    badge: 'new',
    rating: 4.2,
    reviews: 20,
    tone: '#163a66',
    image: '/products/posture-strap.jpg',
  },
  {
    id: 'cane-seat',
    name: 'מקל הליכה עם מושב',
    category: 'home',
    price: 129,
    description: 'מקל שנפתח למושב קל, ומתקפל לנשיאה.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.6,
    reviews: 15,
    tone: '#163a66',
    image: '/products/cane-seat.jpg',
  },
  {
    id: 'crutch',
    name: 'קב בית שחי',
    category: 'home',
    price: 79,
    description: 'קב אלומיניום עם גובה מתכוונן וידית אחיזה.',
    specs: ['פריט תצוגה'],
    stock: 10,
    badge: 'new',
    rating: 4.3,
    reviews: 9,
    tone: '#163a66',
    image: '/products/crutch.jpg',
  },
  {
    id: 'shoulder-immob',
    name: 'מקבע כתף',
    category: 'ortho',
    price: 139,
    description: 'מיתלה רחבה שמחזיקה את הזרוע צמוד לגוף.',
    specs: ['פריט תצוגה'],
    stock: 7,
    badge: 'new',
    rating: 4.5,
    reviews: 8,
    tone: '#163a66',
    image: '/products/shoulder-immob.jpg',
  },
  {
    id: 'knee-pillow',
    name: 'כרית ברכיים לשינה',
    category: 'home',
    price: 89,
    description: 'כרית בין הברכיים לשינה על הצד.',
    specs: ['פריט תצוגה'],
    stock: 14,
    badge: 'new',
    rating: 4.6,
    reviews: 23,
    tone: '#163a66',
    image: '/products/knee-pillow.jpg',
  },
  {
    id: 'ankle-sleeve',
    name: 'שרוול קרסול',
    category: 'ortho',
    price: 45,
    description: 'שרוול אלסטי דק, נלבש כמו גרב קצרה.',
    specs: ['פריט תצוגה'],
    stock: 22,
    badge: 'new',
    rating: 4.4,
    reviews: 31,
    tone: '#163a66',
    image: '/products/ankle-sleeve.jpg',
  },
  {
    id: 'quad-cane',
    name: 'מקל הליכה ארבע רגליים',
    category: 'home',
    price: 99,
    description: 'מקל עם בסיס רחב לאחיזה יציבה יותר.',
    specs: ['פריט תצוגה'],
    stock: 9,
    badge: 'new',
    rating: 4.5,
    reviews: 12,
    tone: '#163a66',
    image: '/products/quad-cane.jpg',
  },
  {
    id: 'knee-sleeve',
    name: 'שרוול ברך',
    category: 'ortho',
    price: 55,
    description: 'שרוול אלסטי לברך, בלי צירים ובלי מתכת.',
    specs: ['פריט תצוגה'],
    stock: 20,
    badge: 'new',
    rating: 4.4,
    reviews: 28,
    tone: '#163a66',
    image: '/products/knee-sleeve.jpg',
  },
  {
    id: 'air-ankle',
    name: 'סד קרסול מתנפח',
    category: 'ortho',
    price: 129,
    description: 'סד עם כרית אוויר שמהדקים סביב הקרסול.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.5,
    reviews: 10,
    tone: '#163a66',
    image: '/products/air-ankle.jpg',
  },
  {
    id: 'thumb-splint',
    name: 'סד אגודל',
    category: 'ortho',
    price: 99,
    description: 'סד שמייצב את האגודל ומשאיר את שאר האצבעות פנויות.',
    specs: ['פריט תצוגה'],
    stock: 11,
    badge: 'new',
    rating: 4.5,
    reviews: 13,
    tone: '#163a66',
    image: '/products/thumb-splint.jpg',
  },
  {
    id: 'finger-ext',
    name: 'סד אצבעות',
    category: 'ortho',
    price: 119,
    description: 'סד עם רצועות לאצבעות ולשורש כף היד.',
    specs: ['פריט תצוגה'],
    stock: 6,
    badge: 'new',
    rating: 4.3,
    reviews: 7,
    tone: '#163a66',
    image: '/products/finger-ext.jpg',
  },
  {
    id: 'knee-open',
    name: 'מייצב ברך עם פתח',
    category: 'ortho',
    price: 159,
    description: 'מייצב עם פתח לפיקה ורצועות סקוטש.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.6,
    reviews: 16,
    tone: '#163a66',
    image: '/products/knee-open.jpg',
  },
  {
    id: 'wrist-wrap',
    name: 'סד שורש כף יד כרוך',
    category: 'ortho',
    price: 109,
    description: 'רצועה רחבה שנכרכת על כף היד ועל האמה.',
    specs: ['פריט תצוגה'],
    stock: 9,
    badge: 'new',
    rating: 4.4,
    reviews: 11,
    tone: '#163a66',
    image: '/products/wrist-wrap.jpg',
  },
  {
    id: 'knee-rom',
    name: 'סד ברך עם כוונון',
    category: 'ortho',
    price: 890,
    description: 'סד עם חוגה לטווח כיפוף ויישור. ציוד תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 3,
    badge: 'new',
    rating: 4.7,
    reviews: 6,
    tone: '#163a66',
    image: '/products/knee-rom.jpg',
  },
  {
    id: 'wrist-sleeve',
    name: 'שרוול שורש כף יד',
    category: 'ortho',
    price: 49,
    description: 'שרוול אלסטי עם פתח לאגודל.',
    specs: ['פריט תצוגה'],
    stock: 18,
    badge: 'new',
    rating: 4.3,
    reviews: 19,
    tone: '#163a66',
    image: '/products/wrist-sleeve.jpg',
  },
  {
    id: 'shoulder-rom',
    name: 'סד כתף עם כוונון',
    category: 'ortho',
    price: 1290,
    description: 'סד כתף עם חוגה ומנח לזרוע. פריט תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 2,
    badge: 'new',
    rating: 4.6,
    reviews: 4,
    tone: '#163a66',
    image: '/products/shoulder-rom.jpg',
  },
  {
    id: 'cam-boot',
    name: 'מגף הליכה',
    category: 'ortho',
    price: 249,
    description: 'מגף קשיח עם סוליה וסקוטש, להליכה בבית.',
    specs: ['פריט תצוגה'],
    stock: 6,
    badge: 'new',
    rating: 4.5,
    reviews: 9,
    tone: '#163a66',
    image: '/products/cam-boot.jpg',
  },
  {
    id: 'post-shoe',
    name: 'נעל לאחר ניתוח',
    category: 'ortho',
    price: 149,
    description: 'נעל פתוחה עם סוליה קשיחה ורצועות סגירה.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.4,
    reviews: 8,
    tone: '#163a66',
    image: '/products/post-shoe.jpg',
  },
  {
    id: 'knee-soft',
    name: 'תומך ברך רך',
    category: 'ortho',
    price: 59,
    description: 'תומך בד עם אזור פתוח סביב הברך.',
    specs: ['פריט תצוגה'],
    stock: 16,
    badge: 'new',
    rating: 4.4,
    reviews: 22,
    tone: '#163a66',
    image: '/products/knee-soft.jpg',
  },
  {
    id: 'rollator',
    name: 'הליכון עם מושב',
    category: 'home',
    price: 459,
    description: 'הליכון ארבעה גלגלים עם מושב וידיות בלם.',
    specs: ['פריט תצוגה'],
    stock: 5,
    badge: 'new',
    rating: 4.7,
    reviews: 14,
    tone: '#163a66',
    image: '/products/rollator.jpg',
  },
  {
    id: 'night-splint',
    name: 'סד לילה לכף הרגל',
    category: 'ortho',
    price: 129,
    description: 'סד שננעל על כף הרגל למנוחה בלילה.',
    specs: ['פריט תצוגה'],
    stock: 7,
    badge: 'new',
    rating: 4.3,
    reviews: 10,
    tone: '#163a66',
    image: '/products/night-splint.jpg',
  },
  {
    id: 'wheel-fold',
    name: 'כסא גלגלים חשמלי מתקפל',
    category: 'home',
    price: 4590,
    description: 'כסא חשמלי קומפקטי עם שלט יד. פריט תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 2,
    badge: 'new',
    rating: 4.8,
    reviews: 6,
    tone: '#163a66',
    image: '/products/wheel-fold.jpg',
  },
  {
    id: 'sleep-pillow',
    name: 'כרית שינה ארגונומית',
    category: 'home',
    price: 129,
    description: 'כרית עם אזור אוורור, לשינה על הגב או על הצד.',
    specs: ['פריט תצוגה'],
    stock: 12,
    badge: 'new',
    rating: 4.5,
    reviews: 18,
    tone: '#163a66',
    image: '/products/sleep-pillow.jpg',
  },
  {
    id: 'rehab-shoe',
    name: 'נעל שיקום',
    category: 'ortho',
    price: 169,
    description: 'נעל רחבה עם שלוש רצועות סקוטש וסוליה יציבה.',
    specs: ['פריט תצוגה'],
    stock: 8,
    badge: 'new',
    rating: 4.4,
    reviews: 9,
    tone: '#163a66',
    image: '/products/rehab-shoe.jpg',
  },
  {
    id: 'wrist-brace',
    name: 'סד שורש כף יד עם סקוטש',
    category: 'ortho',
    price: 89,
    description: 'סד עם כמה רצועות, נלבש על כף היד.',
    specs: ['פריט תצוגה'],
    stock: 11,
    badge: 'new',
    rating: 4.5,
    reviews: 15,
    tone: '#163a66',
    image: '/products/wrist-brace.jpg',
  },
  {
    id: 'walker-wheels',
    name: 'הליכון עם גלגלים',
    category: 'home',
    price: 229,
    description: 'הליכון קל עם שני גלגלים קדמיים וידיות.',
    specs: ['פריט תצוגה'],
    stock: 6,
    badge: 'new',
    rating: 4.5,
    reviews: 11,
    tone: '#163a66',
    image: '/products/walker-wheels.jpg',
  },
  {
    id: 'elbow-band',
    name: 'רצועת מרפק',
    category: 'ortho',
    price: 39,
    description: 'רצועה צרה סביב המרפק, מתכווננת בסקוטש.',
    specs: ['פריט תצוגה'],
    stock: 20,
    badge: 'new',
    rating: 4.2,
    reviews: 17,
    tone: '#163a66',
    image: '/products/elbow-band.jpg',
  },
  {
    id: 'torso-brace',
    name: 'חגורת גב קשיחה',
    category: 'ortho',
    price: 189,
    description: 'חגורה עם חיזוק קדמי, נלבשת מעל חולצה.',
    specs: ['פריט תצוגה'],
    stock: 6,
    badge: 'new',
    rating: 4.5,
    reviews: 8,
    tone: '#163a66',
    image: '/products/torso-brace.jpg',
  },
  {
    id: 'grab-steel',
    name: 'מעקה אחיזה מנירוסטה',
    category: 'home',
    price: 199,
    description: 'מעקה קבוע מנירוסטה, לעיגון ליד אסלה או מקלחת.',
    specs: ['פריט תצוגה'],
    stock: 5,
    badge: 'new',
    rating: 4.6,
    reviews: 7,
    tone: '#163a66',
    image: '/products/grab-steel.jpg',
  },
  {
    id: 'shoulder-soft',
    name: 'תומך כתף',
    category: 'ortho',
    price: 79,
    description: 'שרוול רך עם רצועה אלכסונית על הכתף.',
    specs: ['פריט תצוגה'],
    stock: 12,
    badge: 'new',
    rating: 4.3,
    reviews: 13,
    tone: '#163a66',
    image: '/products/shoulder-soft.jpg',
  },
  {
    id: 'wheel-manual',
    name: 'כסא גלגלים ידני',
    category: 'home',
    price: 890,
    description: 'כסא עם גלגלים גדולים להנעה עצמית. פריט תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 4,
    badge: 'new',
    rating: 4.6,
    reviews: 12,
    tone: '#163a66',
    image: '/products/wheel-manual.jpg',
  },
  {
    id: 'thumb-short',
    name: 'סד אגודל קצר',
    category: 'ortho',
    price: 69,
    description: 'סד קצר שעוטף את האגודל ואת שורש כף היד.',
    specs: ['פריט תצוגה'],
    stock: 14,
    badge: 'new',
    rating: 4.4,
    reviews: 16,
    tone: '#163a66',
    image: '/products/thumb-short.jpg',
  },
  {
    id: 'toilet-seat',
    name: 'הגבהה לאסלה',
    category: 'home',
    price: 249,
    description: 'מושב מוגבה עם ידיות צד, מונח על אסלה קיימת.',
    specs: ['פריט תצוגה'],
    stock: 6,
    badge: 'new',
    rating: 4.5,
    reviews: 10,
    tone: '#163a66',
    image: '/products/toilet-seat.jpg',
  },
  {
    id: 'commode',
    name: 'כיסא שירותים',
    category: 'home',
    price: 690,
    description: 'כיסא עם דלי וגלגלים, לשימוש ליד המיטה.',
    specs: ['פריט תצוגה'],
    stock: 4,
    badge: 'new',
    rating: 4.5,
    reviews: 8,
    tone: '#163a66',
    image: '/products/commode.jpg',
  },
  {
    id: 'hip-rom',
    name: 'סד ירך עם כוונון',
    category: 'ortho',
    price: 1490,
    description: 'סד ירך עם חוגה ורצועות לירך ולמותן. פריט תצוגה.',
    specs: ['פריט תצוגה'],
    stock: 2,
    badge: 'new',
    rating: 4.6,
    reviews: 4,
    tone: '#163a66',
    image: '/products/hip-rom.jpg',
  },
]

function line(id: string, qty: number): OrderItem {
  const product = PRODUCTS.find((item) => item.id === id)
  if (!product) throw new Error(`מוצר חסר: ${id}`)
  return { productId: product.id, name: product.name, price: product.price, qty }
}

function buildSeed(
  id: string,
  createdAt: string,
  status: OrderStatus,
  customer: Customer,
  entries: Array<[string, number]>,
  coupon?: string,
): Order {
  const items = entries.map(([productId, qty]) => line(productId, qty))
  const subtotal = items.reduce((sum, item) => sum + item.price * item.qty, 0)
  const priced = quote(subtotal, coupon === 'DEMO10')
  return { id, createdAt, status, customer, items, ...priced, coupon }
}

export const SEED_ORDERS: Order[] = [
  buildSeed(
    'MED-10041',
    '2026-09-20T09:30:00.000Z',
    'delivered',
    { name: 'דנה לדוגמה', phone: '050-0000001', city: 'תל אביב', address: 'רחוב ההדגמה 1' },
    [
      ['thermo', 1],
      ['gel', 2],
    ],
  ),
  buildSeed(
    'MED-10042',
    '2026-09-24T14:10:00.000Z',
    'shipped',
    { name: 'יונתן לדוגמה', phone: '050-0000002', city: 'חיפה', address: 'שדרות הדמו 12' },
    [
      ['bp', 1],
      ['knee', 1],
    ],
    'DEMO10',
  ),
  buildSeed(
    'MED-10043',
    '2026-09-26T11:05:00.000Z',
    'packing',
    { name: 'מיכל לדוגמה', phone: '050-0000003', city: 'ירושלים', address: 'סמטת התצוגה 4' },
    [['neb', 1]],
  ),
  buildSeed(
    'MED-10044',
    '2026-09-28T07:45:00.000Z',
    'received',
    { name: 'עומר לדוגמה', phone: '050-0000004', city: 'באר שבע', address: 'כיכר המדף 8' },
    [
      ['vd', 2],
      ['plasters', 1],
    ],
  ),
]

export const STATUS_FLOW: OrderStatus[] = ['received', 'packing', 'shipped', 'delivered']

export const STATUS_LABEL: Record<OrderStatus, string> = {
  received: 'התקבלה',
  packing: 'נארזת',
  shipped: 'יצאה למשלוח',
  delivered: 'נמסרה',
  cancelled: 'בוטלה',
}

export function productImage(product: string | { id: string; image?: string }) {
  if (typeof product === 'string') return `/products/${product}.png`
  return product.image || `/products/${product.id}.png`
}

export function getProduct(id: string) {
  return PRODUCTS.find((product) => product.id === id)
}

export function getCategory(id: string) {
  return CATEGORIES.find((category) => category.id === id)
}
